name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
#    - name: Build
#      run: cargo make build-web -p release

    - name: Debugging with tmate
      uses: mxschmitt/action-tmate@v3.5
